/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perbandinganvrptw;

import Model.KromosomPopulasi;
import Model.DataTujuan;
import Kontroller.ES;
import Kontroller.DokumenManager;
import java.io.File;
import java.util.ArrayList;
import java.util.Random;
import java.util.concurrent.TimeUnit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class VRPTW_ES extends javax.swing.JFrame {

    /**
     * Creates new form VRPTW_ES
     */
    
    private final int[][] dataPelangganNumber = new int[34][7];
    private final String[][] dataNamaPelanggan = new String[34][2];
    private final int[][] dataJarakNumber = new int[35][35];
    
    public VRPTW_ES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Populasi = new javax.swing.JTextField();
        konstanta = new javax.swing.JTextField();
        Generasi = new javax.swing.JTextField();
        Kapasitas = new javax.swing.JTextField();
        kecepatan = new javax.swing.JTextField();
        parameter_a = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Btn_Load_Data = new javax.swing.JButton();
        Btn_Proses_ES = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        individu_ES = new javax.swing.JLabel();
        fitness_ES = new javax.swing.JLabel();
        terlewati_ES = new javax.swing.JLabel();
        kendaraan_ES = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tampil_kromosom = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelFitnessSeluruh = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        FitnessLama = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        FitnessBaru = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        DataTujuan = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ExecutionTime = new javax.swing.JLabel();
        Bersih_Data = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Parameter"));

        jLabel2.setText("Ukuran Populasi");

        jLabel4.setText("konstanta");

        jLabel5.setText("Jumlah Generasi");

        jLabel6.setText("Kecepatan Kendaraan");

        jLabel7.setText("Kapasitas Angkut");

        jLabel13.setText("Parameter a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Populasi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(konstanta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Generasi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(parameter_a, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(kecepatan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Populasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(konstanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Generasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kecepatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(parameter_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Proses Evolution Strategies");

        Btn_Load_Data.setText("Load FIle");
        Btn_Load_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Load_DataActionPerformed(evt);
            }
        });

        Btn_Proses_ES.setText("Proses Evolution Strategies");
        Btn_Proses_ES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Proses_ESActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Hasil Kromosom Terbaik"));
        jPanel5.setName(""); // NOI18N

        individu_ES.setText("Individu ");

        fitness_ES.setText("Fitness");

        terlewati_ES.setText("Terlewati");

        kendaraan_ES.setText("Banyak kendaraan");

        tampil_kromosom.setText("Banyak Kromosom");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampil_kromosom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tampil_kromosom)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(terlewati_ES)
                            .addComponent(kendaraan_ES)
                            .addComponent(individu_ES)
                            .addComponent(fitness_ES))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(individu_ES)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(fitness_ES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(terlewati_ES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kendaraan_ES)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));

        TabelFitnessSeluruh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Individu", "Kromosom", "Jumlah Kendaraan ", "Terlewati", "Fitness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelFitnessSeluruh);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hasi Fitness Keseluruhan", jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));

        jLabel14.setText("Hasil Fitness Populasi Lama");

        FitnessLama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Individu", "Kromosom", "Jumlah Kendaraan ", "Terlewati", "Fitness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(FitnessLama);

        jLabel15.setText("Hasil Fitness Populasi Baru");

        FitnessBaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Individu", "Kromosom", "Jumlah Kendaraan ", "Terlewati", "Fitness"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(FitnessBaru);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Hasil Fitness Populasi Awal dan Baru", jPanel4);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 255, 255)));

        DataTujuan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Individu", "Kendaraan ", "Kromosom", "Rute", "Waktu", "Sampai", "Buka", "Tunggu", "Mulai", "Layanan", "Selesai", "Tutup", "Penalti"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(DataTujuan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Tujuan Kendaraan", jPanel3);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        ExecutionTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExecutionTime.setText("Execution Time :");

        Bersih_Data.setText("Bersihkan Data");
        Bersih_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bersih_DataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Btn_Load_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Proses_ES, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bersih_Data, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTabbedPane1)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ExecutionTime, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ExecutionTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Btn_Load_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Proses_ES, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bersih_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Load_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Load_DataActionPerformed
        // TODO add your handling code here:
        ArrayList<ArrayList> data;
        
        Populasi.setText(String.valueOf(5));
        konstanta.setText(String.valueOf(1));
        Generasi.setText(String.valueOf(100));
        Kapasitas.setText(String.valueOf(1680));
        kecepatan.setText(String.valueOf(30));
        parameter_a.setText(String.valueOf(0.83));
        
        DokumenManager dokManager = new DokumenManager();
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        
        if(result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println("Selected file : " + selectedFile.getAbsolutePath());
            String nama_file = selectedFile.getName();
            
            if(nama_file.lastIndexOf(".") != -1 && nama_file.lastIndexOf(".") != 0 && nama_file.substring(nama_file.lastIndexOf(".")+1).equals("xlsx")){
                String FILE_NAME = selectedFile.getAbsolutePath();
                data = dokManager.get_data(FILE_NAME);

                //System.out.println(data.size());

                if(selectedFile.getName().equals("datapelanggan.xlsx")){
                    for(int i=0; i<34; i++){
                        for(int j=0; j<9; j++){
                            if(j < 7){
                                dataPelangganNumber[i][j] = Integer.valueOf(data.get(i+1).get(j).toString());
                            }
                            else{
                                dataNamaPelanggan[i][j-7] = data.get(i+1).get(j).toString();
                            }
                            //System.out.println(dataPelanggan[i][j]);
                        }
                        //System.out.println();
                    }
                    JOptionPane.showMessageDialog(null, "datapelanggan.xlsx berhasil diload");
                }
                else if(selectedFile.getName().equals("datajarak.xlsx")){
                    for(int i=0; i<35; i++){
                        for(int j=0; j<35; j++){
                            dataJarakNumber[i][j] = Integer.valueOf(data.get(i+1).get(j+1).toString());
                            //System.out.println("Data ke-" + i + ": " + dataJarak[i][j]);
                        }
                        //System.out.println();
                    }
                    JOptionPane.showMessageDialog(null, "datajarak.xlsx berhasil diload");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "file yang anda pilih bukan file excel");
            }
        }
    }//GEN-LAST:event_Btn_Load_DataActionPerformed

    private void Btn_Proses_ESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Proses_ESActionPerformed
        // TODO add your handling code here:
        long startTime = System.nanoTime(); 
        
        int i,j,k,l;
        
        if(Math.ceil(Double.parseDouble(konstanta.getText())) != Math.floor(Double.parseDouble(konstanta.getText()))){
            JOptionPane.showMessageDialog(null, "Proses perhitungan gagal, nilai konstanta tidak boleh berupa desimal");
        }
        else if(Double.parseDouble(parameter_a.getText()) >= 0.85 && Double.parseDouble(parameter_a.getText())<1 && Integer.parseInt(Generasi.getText()) <= 30){
            JOptionPane.showMessageDialog(null, "Proses perhitungan gagal, nilai parameter a harus berada pada range 0.85 < parameter a < 1 dengan generasi > 30");
        }
        else if(Double.parseDouble(parameter_a.getText()) >= 0.0 && Double.parseDouble(parameter_a.getText())<0.86 && Integer.parseInt(Generasi.getText()) > 30){
            JOptionPane.showMessageDialog(null, "Proses perhitungan gagal, nilai parametser a harus berada pada range 0 <= parameter a <= 0.85 dengan generasi <= 30");
        }
        else{
            int populasi = Integer.parseInt(Populasi.getText());
            int Konstanta = Integer.parseInt(konstanta.getText());
            int generasi = Integer.parseInt(Generasi.getText());
            int kapasitas = Integer.parseInt(Kapasitas.getText());
            int Kec = Integer.parseInt(kecepatan.getText());
            double par_a = Double.parseDouble(parameter_a.getText());
            ES es = new ES();
            es.setUkuranPopulasi(populasi);
            es.setKonstanta(Konstanta);
            es.setParameter_a(par_a);
            es.setKecepatan(Kec);
            es.setKapasitasAngkut(kapasitas); 
            es.setGenerasi(generasi);

            double[] atrnStngh;
            KromosomPopulasi kp, kp_all;

            DataTujuan dataTujuan;
            ArrayList<ArrayList> dataPopulasiTujuankendaraan;

            ArrayList<KromosomPopulasi> kpListLama, kpListBaru;
            ArrayList<double[]> aturanSengah;

            es.insialisasiData(dataPelangganNumber, dataJarakNumber);
            es.populasiAwal();
            es.pembagianKendaraan();
            es.rute_kendaraan();
            es.hitungFitness();

            for(i=0; i<generasi; i++){
                if(i == generasi-1){
                    es.setkromosomPopulasiLama();
                    es.doMutasi();
                    es.pembagianKendaraan();
                    es.rute_kendaraan();
                    es.hitungFitness();
                    es.setKromosomTerbaik();
                    es.setAturanSetengah();

                    kpListLama = es.getKromosomListLama();
                    kpListBaru = es.getKromosomListBaru();
                    dataPopulasiTujuankendaraan = es.getDataTujuan();
                    aturanSengah = es.getAturanSetengah();

                    /*String[] row = new String[7];

                    DefaultTableModel Fitness_Seluruh = (DefaultTableModel) TabelFitnessSeluruh.getModel();
                    for(i=0; i<kpListBaru.size(); i++){
                        kp_all = kpListBaru.get(i);
                        atrnStngh = aturanSengah.get(i);

                        row[0] = String.valueOf(kp_all.getIndividu()+1);
                        row[1] = String.valueOf(kp_all.getjumlahKendaraan());
                        row[2] = String.valueOf(kp_all.getjumlahTerlewati());
                        row[3] = String.valueOf(kp_all.getFitness());

                        if(i < populasi){
                            row[4] = String.valueOf(atrnStngh[0]);
                            row[5] = String.valueOf(atrnStngh[1]);
                            row[6] = String.valueOf(atrnStngh[2]);
                        }else{
                            if(atrnStngh[0] == -2){                    
                                row[4] = "<";
                                row[5] = String.valueOf(atrnStngh[1]);
                                row[6] = String.valueOf(atrnStngh[2]);
                            }else if(atrnStngh[0] == -1){                    
                                row[4] = ">";
                                row[5] = String.valueOf(atrnStngh[1]);
                                row[6] = String.valueOf(atrnStngh[2]);
                            }
                        }


                        Fitness_Seluruh.addRow(row);
                    }*/

                    String[] row = new String[5];

                    DefaultTableModel Fitness_Seluruh = (DefaultTableModel) TabelFitnessSeluruh.getModel();
                    for(j=0; j<kpListBaru.size(); j++){
                        kp_all = kpListBaru.get(j);
                        kp_all.setKromosomString();

                        row[0] = String.valueOf(kp_all.getIndividu()+1);
                        row[1] = kp_all.getkromosomString();
                        row[2] = String.valueOf(kp_all.getjumlahKendaraan());
                        row[3] = String.valueOf(kp_all.getjumlahTerlewati());
                        row[4] = String.valueOf(kp_all.getFitness());

                        Fitness_Seluruh.addRow(row);
                    }

                    row = new String[5];
                    DefaultTableModel Fitness_Lama_Model = (DefaultTableModel) FitnessLama.getModel();
                    for(j=0; j<kpListLama.size(); j++){
                        kp_all = kpListLama.get(j);
                        kp_all.setKromosomString();

                        row[0] = String.valueOf(kp_all.getIndividu()+1);
                        row[1] = kp_all.getkromosomString();
                        row[2] = String.valueOf(kp_all.getjumlahKendaraan());
                        row[3] = String.valueOf(kp_all.getjumlahTerlewati());
                        row[4] = String.valueOf(kp_all.getFitness());

                        Fitness_Lama_Model.addRow(row);
                    }

                    row = new String[5];
                    DefaultTableModel Fitness_Baru_Model = (DefaultTableModel) FitnessBaru.getModel();
                    for(j=0; j<kpListBaru.size(); j++){
                        kp_all = kpListBaru.get(j);
                        kp_all.setKromosomString();

                        row[0] = String.valueOf(kp_all.getIndividu()+1);
                        row[1] = kp_all.getkromosomString();
                        row[2] = String.valueOf(kp_all.getjumlahKendaraan());
                        row[3] = String.valueOf(kp_all.getjumlahTerlewati());
                        row[4] = String.valueOf(kp_all.getFitness());

                        Fitness_Baru_Model.addRow(row);
                    }

                    row = new String[13];
                    DefaultTableModel Data_Tujuan_Model = (DefaultTableModel) DataTujuan.getModel();
                    for(j=0; j<dataPopulasiTujuankendaraan.size(); j++){
                        ArrayList<ArrayList> dataTujuanKendaraan = dataPopulasiTujuankendaraan.get(j);

                        for(k=0; k<dataTujuanKendaraan.size(); k++){
                            ArrayList<DataTujuan> dataTujuans = dataTujuanKendaraan.get(k);

                            for(l=0; l<dataTujuans.size(); l++){
                                dataTujuan = dataTujuans.get(l);

                                row[0] = "P"+String.valueOf(j+1);
                                row[1] = "K"+String.valueOf(k+1); 
                                row[2] = String.valueOf(Integer.parseInt(dataTujuan.getNode()));
                                row[3] = dataNamaPelanggan[Integer.parseInt(dataTujuan.getNode())-1][1];
                                row[4] = dataTujuan.getWaktu();
                                row[5] = dataTujuan.getSampai();
                                row[6] = dataTujuan.getBuka();
                                row[7] = dataTujuan.getTunggu();
                                row[8] = dataTujuan.getMulai();
                                row[9] = dataTujuan.getLayanan();
                                row[10] = dataTujuan.getSelesai();
                                row[11] = dataTujuan.getTutup();
                                row[12] = dataTujuan.getPenalti();

                                Data_Tujuan_Model.addRow(row);
                            }
                        }
                    }

                    kp = es.getKromosomTerbaik();

                    es.set_fitnessTerbaik(kp.getFitness());

                    int individu = kp.getIndividu()+1;
                    individu_ES.setText("Individu : "+individu);
                    tampil_kromosom.setText("Kromosom : "+kp.getkromosomString());
                    fitness_ES.setText("Fitness : "+kp.getFitness());
                    terlewati_ES.setText("Terlewati : "+kp.getjumlahTerlewati());
                    kendaraan_ES.setText("Jumlah Kendaraan : "+kp.getjumlahKendaraan());
                }
                else{
                    es.doMutasi();
                    es.pembagianKendaraan();
                    es.rute_kendaraan();
                    es.hitungFitness();
                    es.setPopulasiKromosomBaru();
                }
            }

            long elapsedTime = System.nanoTime() - startTime;

            double elapsedTimeInSeconds = TimeUnit.MILLISECONDS.convert(elapsedTime, TimeUnit.NANOSECONDS) / 1000.0;

            es.set_waktuKomputasi(elapsedTimeInSeconds);
            if(es.get_jumlahDataDababaseES() == 0){
                es.simpan_parameterHasilES();
            }
            else{
                es.update_parameterHasilES();
            }

            ExecutionTime.setText("Execution Time : "+String.valueOf(elapsedTimeInSeconds)+" detik");

            JOptionPane.showMessageDialog(null, "Proses Perhitungan VRPTV untuk algoritma Evolution Strategies Berhasil");
        }
    }//GEN-LAST:event_Btn_Proses_ESActionPerformed

    private void Bersih_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bersih_DataActionPerformed
        // TODO add your handling code here:
        int i;
        ES es = new ES();
        es.bersihkanData();
        
        DefaultTableModel Fitness_Seluruh = (DefaultTableModel) TabelFitnessSeluruh.getModel();
        for(i=TabelFitnessSeluruh.getRowCount()-1; i>=0; i--){
            Fitness_Seluruh.removeRow(i);
        }
        
        DefaultTableModel Fitness_Lama_Model = (DefaultTableModel) FitnessLama.getModel();
        for(i=FitnessLama.getRowCount()-1; i>=0; i--){
            Fitness_Lama_Model.removeRow(i);
        }
        
        DefaultTableModel Fitness_Baru_Model = (DefaultTableModel) FitnessBaru.getModel();
        for(i=FitnessBaru.getRowCount()-1; i>=0; i--){
            Fitness_Baru_Model.removeRow(i);
        }
        
        DefaultTableModel Data_Tujuan_Model = (DefaultTableModel) DataTujuan.getModel();
        for(i=DataTujuan.getRowCount()-1; i>=0; i--){          
            Data_Tujuan_Model.removeRow(i); 
        }
        
        individu_ES.setText("Individu : ");
        tampil_kromosom.setText("Kromosom : ");
        fitness_ES.setText("Fitness : ");
        terlewati_ES.setText("Terlewati : ");
        kendaraan_ES.setText("Jumlah Kendaraan : ");
    }//GEN-LAST:event_Bersih_DataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRPTW_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRPTW_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRPTW_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRPTW_ES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VRPTW_ES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bersih_Data;
    private javax.swing.JButton Btn_Load_Data;
    private javax.swing.JButton Btn_Proses_ES;
    private javax.swing.JTable DataTujuan;
    private javax.swing.JLabel ExecutionTime;
    private javax.swing.JTable FitnessBaru;
    private javax.swing.JTable FitnessLama;
    private javax.swing.JTextField Generasi;
    private javax.swing.JTextField Kapasitas;
    private javax.swing.JTextField Populasi;
    private javax.swing.JTable TabelFitnessSeluruh;
    private javax.swing.JLabel fitness_ES;
    private javax.swing.JLabel individu_ES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField kecepatan;
    private javax.swing.JLabel kendaraan_ES;
    private javax.swing.JTextField konstanta;
    private javax.swing.JTextField parameter_a;
    private javax.swing.JLabel tampil_kromosom;
    private javax.swing.JLabel terlewati_ES;
    // End of variables declaration//GEN-END:variables
}
